// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.15.8
// source: service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type JobDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	StartSeg      int32                  `protobuf:"varint,2,opt,name=StartSeg,proto3" json:"StartSeg,omitempty"`
	SegLen        int32                  `protobuf:"varint,3,opt,name=SegLen,proto3" json:"SegLen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDetailsResponse) Reset() {
	*x = JobDetailsResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDetailsResponse) ProtoMessage() {}

func (x *JobDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDetailsResponse.ProtoReflect.Descriptor instead.
func (*JobDetailsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *JobDetailsResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *JobDetailsResponse) GetStartSeg() int32 {
	if x != nil {
		return x.StartSeg
	}
	return 0
}

func (x *JobDetailsResponse) GetSegLen() int32 {
	if x != nil {
		return x.SegLen
	}
	return 0
}

type JobDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDataResponse) Reset() {
	*x = JobDataResponse{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDataResponse) ProtoMessage() {}

func (x *JobDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDataResponse.ProtoReflect.Descriptor instead.
func (*JobDataResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *JobDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PartialResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	StartSeg      int32                  `protobuf:"varint,2,opt,name=StartSeg,proto3" json:"StartSeg,omitempty"`
	SegLen        int32                  `protobuf:"varint,3,opt,name=SegLen,proto3" json:"SegLen,omitempty"`
	NumPrimes     int32                  `protobuf:"varint,4,opt,name=NumPrimes,proto3" json:"NumPrimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialResults) Reset() {
	*x = PartialResults{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialResults) ProtoMessage() {}

func (x *PartialResults) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialResults.ProtoReflect.Descriptor instead.
func (*PartialResults) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *PartialResults) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *PartialResults) GetStartSeg() int32 {
	if x != nil {
		return x.StartSeg
	}
	return 0
}

func (x *PartialResults) GetSegLen() int32 {
	if x != nil {
		return x.SegLen
	}
	return 0
}

func (x *PartialResults) GetNumPrimes() int32 {
	if x != nil {
		return x.NumPrimes
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aservice\"\a\n" +
	"\x05Empty\"d\n" +
	"\x12JobDetailsResponse\x12\x1a\n" +
	"\bFilePath\x18\x01 \x01(\tR\bFilePath\x12\x1a\n" +
	"\bStartSeg\x18\x02 \x01(\x05R\bStartSeg\x12\x16\n" +
	"\x06SegLen\x18\x03 \x01(\x05R\x06SegLen\"%\n" +
	"\x0fJobDataResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"~\n" +
	"\x0ePartialResults\x12\x1a\n" +
	"\bFilePath\x18\x01 \x01(\tR\bFilePath\x12\x1a\n" +
	"\bStartSeg\x18\x02 \x01(\x05R\bStartSeg\x12\x16\n" +
	"\x06SegLen\x18\x03 \x01(\x05R\x06SegLen\x12\x1c\n" +
	"\tNumPrimes\x18\x04 \x01(\x05R\tNumPrimes2G\n" +
	"\n" +
	"JobService\x129\n" +
	"\n" +
	"JobDetails\x12\x0e.service.Empty\x1a\x1b.service.JobDetailsResponse2T\n" +
	"\x0eJobDataService\x12B\n" +
	"\aJobData\x12\x1b.service.JobDetailsResponse\x1a\x18.service.JobDataResponse0\x012T\n" +
	"\x16CondenseResultsService\x12:\n" +
	"\x0fCondenseResults\x12\x17.service.PartialResults\x1a\x0e.service.Empty2M\n" +
	"\x17StopConsolidatorService\x122\n" +
	"\x10StopConsolidator\x12\x0e.service.Empty\x1a\x0e.service.EmptyB\x10Z\x0eprotoc/serviceb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_proto_goTypes = []any{
	(*Empty)(nil),              // 0: service.Empty
	(*JobDetailsResponse)(nil), // 1: service.JobDetailsResponse
	(*JobDataResponse)(nil),    // 2: service.JobDataResponse
	(*PartialResults)(nil),     // 3: service.PartialResults
}
var file_service_proto_depIdxs = []int32{
	0, // 0: service.JobService.JobDetails:input_type -> service.Empty
	1, // 1: service.JobDataService.JobData:input_type -> service.JobDetailsResponse
	3, // 2: service.CondenseResultsService.CondenseResults:input_type -> service.PartialResults
	0, // 3: service.StopConsolidatorService.StopConsolidator:input_type -> service.Empty
	1, // 4: service.JobService.JobDetails:output_type -> service.JobDetailsResponse
	2, // 5: service.JobDataService.JobData:output_type -> service.JobDataResponse
	0, // 6: service.CondenseResultsService.CondenseResults:output_type -> service.Empty
	0, // 7: service.StopConsolidatorService.StopConsolidator:output_type -> service.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
